COLUMN_ID = 0

COLUMN_SURVEY_QUESTION_ORDER = 2
COLUMN_SURVEY_QUESTION_TEXT = 3
COLUMN_SURVEY_QUESTION_IS_MULTIPLE_CHOICE = 4
COLUMN_SURVEY_QUESTION_IS_OPEN_ENDED = 5

COLUMN_SURVEY_ANSWER_ID = 0
COLUMN_SURVEY_ANSWER_TEXT = 3
COLUMN_SURVEY_ANSWER_EMOJI = 4
