import os

from dotenv import load_dotenv

load_dotenv()

SERVER_ID = int(os.environ.get("SERVER_ID"))
DB_CONNECTION_STRING = os.environ.get("DB_CONNECTION_STRING")
TOKEN = os.environ.get("TOKEN")
WELCOME_SURVEY_ID = int(os.environ.get("WELCOME_SURVEY_ID"))
ADMINISTRATOR_ROLE_ID = int(os.environ.get("ADMINISTRATOR_ROLE_ID"))
PING_UNANSWERED_SURVEY_OLDER_THAN = os.environ.get("PING_UNANSWERED_SURVEY_OLDER_THAN")
DELETE_UNANSWERED_SURVEYS_OLDER_THAN = os.environ.get(
    "DELETE_UNANSWERED_SURVEYS_OLDER_THAN"
)
DELETE_FINISHED_SURVEYS_OLDER_THAN = os.environ.get(
    "DELETE_FINISHED_SURVEYS_OLDER_THAN"
)
BOT_COMMANDS_CHANNEL_ID = int(os.environ.get("BOT_COMMANDS_CHANNEL_ID"))
IMGUR_CLIENT_ID = os.environ.get("IMGUR_CLIENT_ID")
STAT_GRAPH_VALIDITY_DAYS = int(os.environ.get("STAT_GRAPH_VALIDITY_DAYS"))
