name: Main checks
on: pull_request
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Check style
        run: |
          pipenv run isort --check src
          pipenv run black --check src
  run-tests:
    runs-on: ubuntu-latest
    needs: style-check
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy --dev
      - name: Run tests
        run: |
          pipenv run pytest tests
